#!/usr/bin/env node
// Generates src/design-system/tokens.css from src/design-system/tokens.json.
// tokens.json is copied verbatim from the Relic design system; re-run this after updating it:
//   node scripts/build-tokens.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "design-system");
const tokens = JSON.parse(readFileSync(join(dir, "tokens.json"), "utf8"));

// Custom property names keep the design system's names; dots (space-1.5) must be escaped.
const prop = (name) => `--${name.replace(/\./g, "\\.")}`;
const px = (v) => (typeof v === "number" ? `${v}px` : v);

const out = [
  "/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */",
  "",
];

for (const font of tokens.type.fonts) {
  out.push(
    "@font-face {",
    `  font-family: "${font.family}";`,
    `  src: url("/${font.file}") format("woff2");`,
    `  font-weight: ${font.weight};`,
    `  font-style: ${font.style || "normal"};`,
    "  font-display: swap;",
    "}",
  );
}

out.push("", ":root {");
for (const [key, family] of Object.entries(tokens.type.families)) {
  out.push(`  --font-${key}: ${family};`);
}
const firstTheme = tokens.color.themes[0].id;
for (const t of tokens.color.tokens) {
  const value = typeof t.value === "object" ? t.value[firstTheme] : t.value;
  out.push(`  ${prop(t.name)}: ${value};`);
}
for (const family of ["spacing", "radius", "shadow", "size"]) {
  for (const t of tokens[family]?.tokens || []) out.push(`  ${prop(t.name)}: ${px(t.value)};`);
}
out.push("}", "");

// One class per text style, e.g. .text-body, .mono-meta.
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    const family = group.family || (s.name.startsWith("mono-") ? "mono" : "sans");
    out.push(`.${s.name} {`);
    out.push(`  font-family: var(--font-${s.family || family});`);
    out.push(`  font-size: ${px(s.fontSize)};`);
    out.push(`  line-height: ${s.lineHeight};`);
    out.push(`  font-weight: ${s.fontWeight};`);
    if (s.letterSpacing) out.push(`  letter-spacing: ${s.letterSpacing};`);
    if (["mono-section", "mono-badge"].includes(s.name)) out.push("  text-transform: uppercase;");
    out.push("}");
  }
}

writeFileSync(join(dir, "tokens.css"), out.join("\n") + "\n");
console.log(`tokens.css: ${tokens.color.tokens.length} colours, ${tokens.type.groups.reduce((n, g) => n + g.styles.length, 0)} text styles`);
