#!/usr/bin/env bash
# Bootstrap the k3d cluster and install shared infrastructure.
# Idempotent — safe to run again on an existing cluster.
#
# Usage:
#   ./bootstrap.sh [OPTIONS]
#
# Options:
#   --domain DOMAIN                  Base domain (e.g. relic.example.com)
#   --cloudflare-token TOKEN         Cloudflare API token (Tunnel:Edit + DNS:Edit)
#   --cloudflare-account-id ID       Cloudflare account ID
#   --cloudflare-zone-id ID          Cloudflare zone ID for the domain
#   --github-token TOKEN             GitHub PAT for runner registration
#
# Environment variables (alternative to flags):
#   K8S_DOMAIN, CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_ZONE_ID,
#   GITHUB_RUNNER_TOKEN

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
K8S_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/lib/colors.sh"
source "${SCRIPT_DIR}/lib/wait-for.sh"

# ---------------------------------------------------------------------------
# Defaults / argument parsing
# ---------------------------------------------------------------------------
DOMAIN="${K8S_DOMAIN:-relic.example.com}"
CF_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
CF_ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-}"
CF_ZONE_ID="${CLOUDFLARE_ZONE_ID:-}"
GITHUB_TOKEN="${GITHUB_RUNNER_TOKEN:-}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)               DOMAIN="$2";        shift 2 ;;
    --cloudflare-token)     CF_API_TOKEN="$2";  shift 2 ;;
    --cloudflare-account-id) CF_ACCOUNT_ID="$2"; shift 2 ;;
    --cloudflare-zone-id)   CF_ZONE_ID="$2";    shift 2 ;;
    --github-token)         GITHUB_TOKEN="$2";  shift 2 ;;
    *) error "Unknown argument: $1"; exit 1 ;;
  esac
done

SECRETS_FILE="${K8S_DIR}/.cluster-secrets.env"

# ---------------------------------------------------------------------------
# Step 1: Prerequisites
# ---------------------------------------------------------------------------
step "Checking prerequisites"

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    error "Required command not found: $1"
    exit 1
  fi
  success "$1 found ($(command -v "$1"))"
}

check_cmd k3d
check_cmd kubectl
check_cmd jq
check_cmd curl
check_cmd openssl

if ! docker info &>/dev/null; then
  error "Docker is not running"
  exit 1
fi
success "Docker is running"

# ---------------------------------------------------------------------------
# Step 2: Create k3d cluster
# ---------------------------------------------------------------------------
step "Creating k3d cluster"

if k3d cluster list 2>/dev/null | grep -q "^relic "; then
  warn "Cluster 'relic' already exists — skipping creation"
else
  info "Creating cluster from ${K8S_DIR}/k3d-config.yaml"
  k3d cluster create --config "${K8S_DIR}/k3d-config.yaml"
  success "Cluster created"
fi

info "Waiting for nodes to be ready..."
kubectl wait --for=condition=ready node --all --timeout=120s
success "All nodes ready"

# ---------------------------------------------------------------------------
# Step 3: Shared namespace
# ---------------------------------------------------------------------------
step "Creating shared namespace"
kubectl apply -f "${K8S_DIR}/shared/namespace.yaml"

# ---------------------------------------------------------------------------
# Step 5: Generate and persist cluster credentials
# ---------------------------------------------------------------------------
step "Generating cluster credentials"

if [[ -f "${SECRETS_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${SECRETS_FILE}"
else
  PG_ROOT_PASSWORD="$(openssl rand -hex 20)"
  MINIO_ROOT_PASSWORD="$(openssl rand -hex 20)"
fi

# Flags always override stored values
[[ -n "${CF_API_TOKEN}"  ]] && CLOUDFLARE_API_TOKEN="${CF_API_TOKEN}"
[[ -n "${CF_ACCOUNT_ID}" ]] && CLOUDFLARE_ACCOUNT_ID="${CF_ACCOUNT_ID}"
[[ -n "${CF_ZONE_ID}"    ]] && CLOUDFLARE_ZONE_ID="${CF_ZONE_ID}"

# Write (or rewrite) the secrets file with current values
cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by bootstrap.sh — DO NOT COMMIT
PG_ROOT_PASSWORD=${PG_ROOT_PASSWORD}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-}
CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID:-}
DOMAIN=${DOMAIN}
EOF
chmod 600 "${SECRETS_FILE}"
success "Credentials written to ${SECRETS_FILE}"

if [[ -z "${CLOUDFLARE_API_TOKEN:-}" || -z "${CLOUDFLARE_ACCOUNT_ID:-}" || -z "${CLOUDFLARE_ZONE_ID:-}" ]]; then
  warn "Cloudflare credentials not fully set — tunnels cannot be provisioned automatically"
  warn "Re-run bootstrap with --cloudflare-token, --cloudflare-account-id, --cloudflare-zone-id to enable"
fi

# ---------------------------------------------------------------------------
# Step 6: Deploy PostgreSQL
# ---------------------------------------------------------------------------
step "Deploying PostgreSQL"
kubectl create secret generic postgres-secret \
  --namespace shared \
  --from-literal="postgres-password=${PG_ROOT_PASSWORD}" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -f "${K8S_DIR}/shared/postgres/"
kubectl rollout status statefulset/postgres -n shared --timeout=120s
success "PostgreSQL ready"

# ---------------------------------------------------------------------------
# Step 7: Deploy MinIO
# ---------------------------------------------------------------------------
step "Deploying MinIO"
kubectl create secret generic minio-secret \
  --namespace shared \
  --from-literal="root-password=${MINIO_ROOT_PASSWORD}" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl apply -f "${K8S_DIR}/shared/minio/"
kubectl rollout status statefulset/minio -n shared --timeout=120s
success "MinIO ready"

# ---------------------------------------------------------------------------
# Step 8: GitHub Actions runner
# ---------------------------------------------------------------------------
step "Configuring GitHub Actions runner"

kubectl apply -f "${K8S_DIR}/runners/namespace.yaml"
kubectl apply -f "${K8S_DIR}/runners/rbac.yaml"

if [[ -z "${GITHUB_TOKEN}" ]]; then
  warn "No --github-token provided — skipping runner Secret creation"
  warn "Run manually: kubectl create secret generic runner-secret --namespace runners --from-literal=GITHUB_TOKEN=<TOKEN>"
else
  kubectl create secret generic runner-secret \
    --namespace runners \
    --from-literal="GITHUB_TOKEN=${GITHUB_TOKEN}" \
    --dry-run=client -o yaml | kubectl apply -f -
  success "Runner token secret created"
fi

# Store cluster secrets in k8s so the runner pod can access them at provision time
kubectl create secret generic cluster-secrets \
  --namespace runners \
  --from-literal="PG_ROOT_PASSWORD=${PG_ROOT_PASSWORD}" \
  --from-literal="MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}" \
  --from-literal="CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}" \
  --from-literal="CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-}" \
  --from-literal="CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID:-}" \
  --from-literal="DOMAIN=${DOMAIN}" \
  --dry-run=client -o yaml | kubectl apply -f -
success "Cluster secrets stored for runner"

kubectl apply -f "${K8S_DIR}/runners/deployment.yaml"
success "Runner deployed"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
step "Bootstrap complete"
echo ""
info "Cluster: relic"
info "Shared services:"
kubectl get pods -n shared --no-headers 2>/dev/null | awk '{printf "  %-40s %s\n", $1, $3}' || true
echo ""
success "Ready! Create your first environment with:"
echo "  make k8s-deploy K8S_ENV=testing K8S_DOMAIN=${DOMAIN}"
