#!/usr/bin/env bash
# Provision or update a named environment in the k3d cluster.
# Idempotent — safe to run again to update an existing environment.
#
# Usage:
#   ./provision-env.sh --env testing --domain relic.example.com [OPTIONS]
#
# Options:
#   --env ENV          Environment name (testing|dev|demo|pr-<N>|any)
#   --domain DOMAIN    Base domain
#   --version TAG      Image tag to deploy (default: latest)
#   --seed PROFILE     Optional seed profile to run after deploy (e.g. demo, testing)
#   --seed-only        Only run the seed step — skip deploy
#
# Required env vars (or set in .cluster-secrets.env):
#   CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_ZONE_ID

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
K8S_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/lib/colors.sh"
source "${SCRIPT_DIR}/lib/wait-for.sh"
source "${SCRIPT_DIR}/lib/cloudflare.sh"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
ENV=""
DOMAIN="${K8S_DOMAIN:-relic.example.com}"
VERSION="latest"
SEED_PROFILE=""
SEED_ONLY=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --env)       ENV="$2";          shift 2 ;;
    --domain)    DOMAIN="$2";       shift 2 ;;
    --version)   VERSION="$2";      shift 2 ;;
    --seed)      SEED_PROFILE="$2"; shift 2 ;;
    --seed-only) SEED_ONLY=true;    shift ;;
    *) error "Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "${ENV}" ]]; then
  error "Usage: $0 --env <name> --domain <domain> [--version <tag>] [--seed <profile>]"
  exit 1
fi

# Derived values
NAMESPACE="relic-${ENV}"
DB_NAME="relic_$(echo "${ENV}" | tr '-' '_')"
DB_USER="${DB_NAME}_user"
MINIO_BUCKET="relic-${ENV}"
HOSTNAME="${ENV}.${DOMAIN}"
OVERLAY_DIR="${K8S_DIR}/overlays/${ENV}"
TUNNEL_NAME="tunnel-${ENV}"

# Dynamic envs have no checked-in overlay directory.
IS_DYNAMIC_ENV=false
[[ ! -f "${OVERLAY_DIR}/kustomization.yaml" ]] && IS_DYNAMIC_ENV=true

# Load cluster secrets (local runs); runner gets these via env vars from k8s Secret
SECRETS_FILE="${K8S_DIR}/.cluster-secrets.env"
if [[ -f "${SECRETS_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${SECRETS_FILE}"
  info "Loaded cluster credentials from ${SECRETS_FILE}"
fi

cf_check_credentials

# ---------------------------------------------------------------------------
# Seed only
# ---------------------------------------------------------------------------
if "${SEED_ONLY}"; then
  if [[ -z "${SEED_PROFILE}" ]]; then
    error "--seed-only requires --seed <profile>"
    exit 1
  fi
  step "Running seed '${SEED_PROFILE}' against https://${HOSTNAME}"
  RELIC_BASE_URL="https://${HOSTNAME}" bash "${K8S_DIR}/seeds/${SEED_PROFILE}.sh"
  success "Seed '${SEED_PROFILE}' complete"
  exit 0
fi

# ---------------------------------------------------------------------------
# Step 1: Create namespace
# ---------------------------------------------------------------------------
step "Creating namespace: ${NAMESPACE}"
kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

# ---------------------------------------------------------------------------
# Step 2: Provision Cloudflare Tunnel
# ---------------------------------------------------------------------------
SECRETS_ENV_FILE="${OVERLAY_DIR}/secrets/env.sh"

# Check if this env already has a tunnel token (idempotent re-runs)
TUNNEL_TOKEN=""
if [[ -f "${SECRETS_ENV_FILE}" ]]; then
  # shellcheck source=/dev/null
  source "${SECRETS_ENV_FILE}"
  info "Loaded existing credentials from ${SECRETS_ENV_FILE}"
fi

if [[ -z "${TUNNEL_TOKEN:-}" ]]; then
  step "Creating Cloudflare Tunnel: ${TUNNEL_NAME}"
  tunnel_output="$(cf_create_tunnel "${TUNNEL_NAME}")"
  TUNNEL_ID="$(echo "${tunnel_output}" | head -1)"
  TUNNEL_TOKEN="$(echo "${tunnel_output}" | tail -1)"

  step "Creating DNS record: ${HOSTNAME}"
  cf_create_dns_route "${TUNNEL_ID}" "${HOSTNAME}"

  mkdir -p "${OVERLAY_DIR}/secrets"
  cat > "${SECRETS_ENV_FILE}" <<EOF
# Auto-generated by provision-env.sh — DO NOT COMMIT
TUNNEL_TOKEN=${TUNNEL_TOKEN}
TUNNEL_NAME=${TUNNEL_NAME}
TUNNEL_ID=${TUNNEL_ID}
EOF
  chmod 600 "${SECRETS_ENV_FILE}"
  success "Tunnel '${TUNNEL_NAME}' created (${TUNNEL_ID})"
else
  info "Tunnel '${TUNNEL_NAME}' already provisioned — skipping"
fi

# Create/update the cloudflared-token Secret in the env namespace
kubectl create secret generic cloudflared-token \
  --namespace "${NAMESPACE}" \
  --from-literal="token=${TUNNEL_TOKEN}" \
  --dry-run=client -o yaml | kubectl apply -f -

# ---------------------------------------------------------------------------
# Step 3: Provision PostgreSQL database
# ---------------------------------------------------------------------------
step "Provisioning PostgreSQL database: ${DB_NAME}"

# Generate DB password if this is a new environment
if [[ -z "${DB_PASSWORD:-}" ]]; then
  DB_PASSWORD="$(openssl rand -hex 20)"
  cat >> "${SECRETS_ENV_FILE}" <<EOF
DB_PASSWORD=${DB_PASSWORD}
EOF
fi

DB_JOB="provision-db-${ENV}"
kubectl delete job "${DB_JOB}" -n shared --ignore-not-found=true

kubectl apply -f - <<JOB
apiVersion: batch/v1
kind: Job
metadata:
  name: ${DB_JOB}
  namespace: shared
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              export PGPASSWORD="\${PG_ROOT_PASSWORD}"
              psql -h postgres.shared.svc.cluster.local -U postgres -tc \
                "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
                psql -h postgres.shared.svc.cluster.local -U postgres -c \
                  "CREATE DATABASE ${DB_NAME};"
              psql -h postgres.shared.svc.cluster.local -U postgres -tc \
                "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1 || \
                psql -h postgres.shared.svc.cluster.local -U postgres -c \
                  "CREATE USER ${DB_USER} WITH PASSWORD '\${DB_PASSWORD}';"
              psql -h postgres.shared.svc.cluster.local -U postgres -c \
                "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
              psql -h postgres.shared.svc.cluster.local -U postgres -c \
                "ALTER DATABASE ${DB_NAME} OWNER TO ${DB_USER};"
              echo "Done."
          env:
            - name: PG_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
JOB

wait_for_job "${DB_JOB}" shared 2m
success "Database '${DB_NAME}' provisioned"

# ---------------------------------------------------------------------------
# Step 4: Provision MinIO bucket
# ---------------------------------------------------------------------------
step "Provisioning MinIO bucket: ${MINIO_BUCKET}"

MC_JOB="provision-minio-${ENV}"
kubectl delete job "${MC_JOB}" -n shared --ignore-not-found=true

kubectl apply -f - <<JOB
apiVersion: batch/v1
kind: Job
metadata:
  name: ${MC_JOB}
  namespace: shared
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set minio http://minio.shared.svc.cluster.local:9000 minioadmin "\${MINIO_ROOT_PASSWORD}"
              mc mb --ignore-existing "minio/${MINIO_BUCKET}"
              echo "Bucket '${MINIO_BUCKET}' ready."
          env:
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
JOB

wait_for_job "${MC_JOB}" shared 2m
success "Bucket '${MINIO_BUCKET}' provisioned"

# ---------------------------------------------------------------------------
# Step 5: Create overlay directory and secrets
# ---------------------------------------------------------------------------
step "Writing overlay for '${ENV}'"

mkdir -p "${OVERLAY_DIR}/secrets"

# Write the k8s Secret
cat > "${OVERLAY_DIR}/secrets/app-secrets.yaml" <<SECRET
apiVersion: v1
kind: Secret
metadata:
  name: relic-app-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres.shared.svc.cluster.local:5432/${DB_NAME}"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "${MINIO_ROOT_PASSWORD}"
  MINIO_BUCKET: "${MINIO_BUCKET}"
  ALLOWED_ORIGINS: "[\"https://${HOSTNAME}\",\"http://${HOSTNAME}\"]"
  ADMIN_CLIENT_IDS: "${ADMIN_CLIENT_IDS:-}"
SECRET

# For dynamic environments, generate overlay files on the fly
if "${IS_DYNAMIC_ENV}"; then
  cat > "${OVERLAY_DIR}/namespace.yaml" <<NS
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
NS

  cat > "${OVERLAY_DIR}/patch-cloudflared.yaml" <<PATCH
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    ingress:
      - hostname: ${HOSTNAME}
        service: http://frontend:80
      - service: http_status:404
PATCH

  cat > "${OVERLAY_DIR}/kustomization.yaml" <<KUST
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
  - ../../base
  - namespace.yaml
  - secrets/app-secrets.yaml

images:
  - name: ghcr.io/ovidiuvio/relic/backend
    newTag: "${VERSION}"
  - name: ghcr.io/ovidiuvio/relic/frontend
    newTag: "${VERSION}"

patches:
  - path: patch-cloudflared.yaml
    target:
      kind: ConfigMap
      name: cloudflared-config
KUST
else
  # Update image tags for existing overlay
  sed -i "s/newTag: .*/newTag: \"${VERSION}\"/" "${OVERLAY_DIR}/kustomization.yaml"
fi

# For named envs, substitute DOMAIN_PLACEHOLDER with the actual domain
sed -i "s/DOMAIN_PLACEHOLDER/${DOMAIN}/g" "${OVERLAY_DIR}/patch-cloudflared.yaml" 2>/dev/null || true

success "Overlay ready at ${OVERLAY_DIR}"

# ---------------------------------------------------------------------------
# Step 6: Deploy via kustomize
# ---------------------------------------------------------------------------
step "Deploying '${ENV}' (version: ${VERSION})"
kubectl apply -k "${OVERLAY_DIR}"

info "Waiting for backend rollout..."
wait_for_rollout backend "${NAMESPACE}" 5m

info "Waiting for frontend rollout..."
wait_for_rollout frontend "${NAMESPACE}" 5m

success "Deployment complete"

# ---------------------------------------------------------------------------
# Step 7: Optional seed
# ---------------------------------------------------------------------------
if [[ -n "${SEED_PROFILE}" ]]; then
  step "Running seed '${SEED_PROFILE}'"
  RELIC_BASE_URL="https://${HOSTNAME}" bash "${K8S_DIR}/seeds/${SEED_PROFILE}.sh"
  success "Seed '${SEED_PROFILE}' complete"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
step "Environment '${ENV}' is ready"
echo ""
info "  URL:       https://${HOSTNAME}"
info "  Namespace: ${NAMESPACE}"
info "  Tunnel:    ${TUNNEL_NAME}"
info "  Version:   ${VERSION}"
echo ""
info "Useful commands:"
echo "  make k8s-logs K8S_ENV=${ENV}    # stream backend logs"
echo "  make k8s-shell K8S_ENV=${ENV}   # open backend shell"
echo "  make k8s-test K8S_ENV=${ENV}    # run integration tests"
