apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relic-demo

resources:
  - ../../base
  - namespace.yaml
  - secrets/app-secrets.yaml

images:
  - name: ghcr.io/ovidiuvio/relic/backend
    newTag: latest
  - name: ghcr.io/ovidiuvio/relic/frontend
    newTag: latest
    newTag: latest

patches:
  - path: patch-cloudflared.yaml
    target:
      kind: ConfigMap
      name: cloudflared-config
